stages:
  - test

variables:
  DATABASE_URL: "mysql://test_user:test_password@mariadb/test_db" # Connection URL to the MariaDB database

test:
  stage: test
  image: ripitchip/diesel-app:v1.0-mysql-slim-bookworm
  services:
    - name: mariadb:10.5 # Use the same MariaDB service
      alias: mariadb
    - name: mysql:8.0
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: test_db
    MYSQL_USER: test_user
    MYSQL_PASSWORD: test_password
  before_script:
    # Wait until the MariaDB service is ready
    # - until mysqladmin ping -h mariadb --silent; do echo "Waiting for MariaDB..."; sleep 2; done
  script:
    - |
      for sql_dir in $(find migrations -type d -print | sort); do
        if [ -f "$sql_dir/up.sql" ]; then
          echo "Running migration: $sql_dir/up.sql"
          cat "$sql_dir/up.sql" # Display the SQL content
          mysql -h mariadb -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < "$sql_dir/up.sql"
        fi
      done
    - cargo test -- --test-threads=1
