[package]
name = "anybdd"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
diesel = { version = "2.2.2", features = ["mysql","chrono", "r2d2"] }
dotenvy = "0.15.7"
log = "0.4.22"
