FROM rust:slim-bookworm

ENV CARGO_TARGET_DIR=/root/bin
RUN apt-get update
RUN apt-get update && apt-get install -y sudo libmariadb-dev default-libmysqlclient-dev
RUN cargo install diesel_cli --no-default-features --features mysql
